### PR TITLE
Wrokaround wrong public path for w32

### PR DESCRIPTION
**Pull request by zklhp**
Please see appropriate.

### CODE REVIEW

**Comment by Xuanwo** [comment]
looks good, please fix the test at the same time.

**Comment by zklhp** [comment]
Never used CI before. I also fix the warnings in your commit 4e05a72 :smile:.

Thanks.

**Comment by Rememberli** [comment]
Is this accepted ? @Xuanwo

**Comment by Xuanwo** [comment]
LGTM.

**Pull request merged**
